export const DEGREES = ["B.Tech", "B.Arch", "Dual Degree", "M.Tech", "M.Sc", "MBA", "Ph.D", "MS", "MCP", "MMST", "LLB", "LLM", "Other"];
export const DEPARTMENTS = ["Aerospace Engineering", "Advanced Technology Centre", "Agricultural & Food Engineering", "Architecture & Regional Planning", "Biotechnology", "Centre for Theoretical Studies", "Chemical Engineering", "Chemistry", "Civil Engineering", "Computer Science & Engineering", "Cyrogenic Engineering", "Center for Educational Technology", "Energy Science and Engineering", "Energy Engineering", "Electrical Engineering", "Electronics & Electrical Communications Engineering", "Exploration Geophysics", "GS Sanyal School of Telecommunications (GS)", "GS Sanyal School of Telecommunications (TE)", "Geology & Geophysics", "Humanities & Social Sciences", "Industrial Engineering & Management", "Instrumentation Engineering", "School of Information Technology", "Material Science", "Mathematics", "Manufacturing Engineering", "Mechanical Engineering", "Medical Science & Technology", "Metallurgical Engineering", "Mining Engineering", "Ocean Engineering & Naval Architecture", "Ocean, Rivers, Atmosphere & Land Sciences", "Physics & Meteorology", "Quality Engineering Design and Manufacturing", "Rajendra Mishra School of Engineering Entrepreneurship", "Rajeev Gandhi School of Intellectual Property Law", "Ranbir and Chitra Gupta School of Infrastructure Design and Management", "Reliability Engineering", "Rubber Technology Center", "Rural Development Centre", "School of Water Resources", "Steel Technology Centre", "Statistics and Informatics", "Vinod Gupta School of Management", "Other"];
export const HALLS = ["Ashutosh Mukherjee", "Azad", "Bhidan Chandra Roy", "Campus", "Dr. B R Ambedkar", "Gokhale", "Homi J Bhabha", "Jagadish Chandra Bose", "Lala Lajpat Rai", "Lalbahadur Sastry", "Madan Mohan Malaviya", "Meghnad Saha", "Mother Teresa", "Nehru", "Patel", "Radhakrishnan", "Rajendra Prasad", "Rani Laxmi Bai", "Sarojini Naidu / Indira Gandhi", "Vidyasagar", "Zakir Hussain", "Vikram Sarabhai Residential Complex", "Institute Quarter", "Bachelors Flat", "Rader Flats", "Other"];
export const ALL_FIELDS = [
  'firstName', 'lastName', 'email', 'mobile', 'birthdate', 'sex', 
  'maritalStatus', 'yearOfGraduation', 'department', 'degree', 
  'hall', 'currentOccupation', 'residenceAddress', 'officeAddress', 
  'spouseFirstName', 'spouseLastName', 'anniversaryDate', 'numberOfChildren',
  'isLifeMember', 'membershipNumber' 
];